"""users table

Revision ID: 64cc26129489
Revises: 
Create Date: 2018-03-15 22:28:15.871279

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64cc26129489'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('books',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lender', sa.Integer(), nullable=True),
    sa.Column('book_name', sa.String(length=140), nullable=True),
    sa.Column('author', sa.String(length=140), nullable=True),
    sa.Column('genre', sa.String(length=140), nullable=True),
    sa.Column('summary', sa.String(length=140), nullable=True),
    sa.Column('current_status', sa.String(length=140), nullable=True),
    sa.ForeignKeyConstraint(['lender'], ['users.username'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('book_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=True),
    sa.Column('book_name', sa.Integer(), nullable=True),
    sa.Column('borrower', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=140), nullable=True),
    sa.Column('borrow_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], ),
    sa.ForeignKeyConstraint(['book_name'], ['books.book_name'], ),
    sa.ForeignKeyConstraint(['borrower'], ['users.username'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_book_history_borrow_time'), 'book_history', ['borrow_time'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_book_history_borrow_time'), table_name='book_history')
    op.drop_table('book_history')
    op.drop_table('books')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
