"""users table

Revision ID: b2dace5760f0
Revises: 
Create Date: 2018-03-09 20:48:48.973600

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b2dace5760f0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('summary', sa.String(), nullable=True))
    op.drop_column('books', 'lender')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('lender', sa.VARCHAR(), nullable=True))
    op.drop_column('books', 'summary')
    # ### end Alembic commands ###
